### ISSUE TITLE
Sequence download is not working for https://open.cov-spectrum.org

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/cov-spectrum-website#1018] opened 2024-09-04 14:19 UTC
When I click on the Fasta download button on https://open.cov-spectrum.org/explore/Switzerland/AllSamples/Past6M/variants?nextcladePangoLineage=XBB*& 
<img width="340" alt="image" src="https://github.com/user-attachments/assets/4a1776f9-58ee-4b54-90a8-462393c4f5cb">
I get an `Internal Server Error`: 
<img width="607" alt="image" src="https://github.com/user-attachments/assets/6e3225ab-5974-4128-8053-940abf7ce7d0">
Exact links: https://lapis.cov-spectrum.org/open/v2/sample/unalignedNucleotideSequences?orderBy=random&limit=10000&country=Switzerland&dateFrom=2024-03-04&dateTo=2024-08-28&nextcladePangoLineage=XBB*&host=Homo+sapiens&downloadAsFile=true
https://lapis.cov-spectrum.org/open/v2/sample/alignedNucleotideSequences?orderBy=random&limit=10000&country=Switzerland&dateFrom=2024-03-04&dateTo=2024-08-28&nextcladePangoLineage=XBB*&host=Homo+sapiens&downloadAsFile=true

**Comment by fengelniederhammer** [comment] 2024-09-04 14:20
The issue is already fixed by https://github.com/GenSpectrum/LAPIS/issues/890 and needs a deployment of a recent LAPIS version.

**Closed as completed by fengelniederhammer** 2024-09-04 14:20 UTC
