### ISSUE TITLE
ENH: Allow reordering of queries in collection

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#620] opened 2022-10-17 16:45 UTC
The order of queries is quite important if you want plots to have a logical succession like in this case:
<img width="2450" alt="image" src="https://user-images.githubusercontent.com/25161793/196235556-728a571a-53b1-446c-882e-dca5fb633b30.png">

Unfortunately, it's not possible (it seems) to reorder queries. One cannot insert things at the top. Which is a bit of a shame as there doesn't seem to be a way to upload a textfile with the collection (which would allow me to reorder without hundreds of clicks).

It would be great to be able to export/import collection definition files. I'm a bit tired of clicking :D

**Comment by chaoran-chen** [comment] 2022-10-18 08:00
Thanks for the suggestion! This is a duplicate of #523 and #596 - they are on the top of my list.

**Closed as not planned by chaoran-chen** 2022-10-18 08:00 UTC
Labels: duplicate

**Comment by corneliusroemer** [comment] 2022-10-18 10:09
Oh ok, not aware 😬 

I was very happy to see the issue closed with purple check (meaning completed) - I'm closing as not planned/duplicate now to make it clear it's a duplicate
