### ISSUE TITLE
[Enhancement] Allow queries to include non-mutations, e.g. S:Y145Y

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#282] opened 2021-10-21 19:30 UTC
It would be great if one could query for non-mutations, like give me all Delta that lack S:L452R by searching for something like: `B.1.617.2*, S:452L`

Would this be possible to implement? it shouldn't be too hard, should it?

**Comment by chaoran-chen** [comment] 2021-10-21 19:43
It is already possible in the preview? And it's a duplicate of #206 ;)

As a bonus, you don't even need to type in the base of the reference genome, but can write `.` instead. In your example: `S:452.`

**Closed as completed by chaoran-chen** 2021-10-21 19:43 UTC
Labels: duplicate

**Comment by corneliusroemer** [comment] 2021-10-21 20:09
Wohoo!
