### ISSUE TITLE
BUG: notation that a position is not mutated (such as S:501.) does not work in advanced query

### ISSUE THREAD

**Issue by AnonymousUserUse** [GenSpectrum/cov-spectrum-website#637] opened 2022-11-06 16:25 UTC
.-notation for a non-mutated position (such as S:501.) works in simple module:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=S%3A501.

but nor in advanced query:
https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=S%3A501.&

The same applies to nucleotide mutation.

**Comment by chaoran-chen** [comment] 2022-11-07 06:29
Hi @AnonymousUserUse, that's indeed missing and still on the todo list. I'm just closing this issue as it is a duplicate of #439.

**Closed as not planned** 2022-11-07 06:30 UTC
