### ISSUE TITLE
BUG: Alias not showing for Nextclade lineages, only for pangoLEARN/GISAID

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#625] opened 2022-10-21 12:24 UTC
I've noticed that the "Alias for" doesn't show for Nextclade, only for pangoLEARN

<img width="979" alt="image" src="https://user-images.githubusercontent.com/25161793/197194953-74fc5216-7945-4a05-824d-13dde671c63e.png">

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/25161793/197194956-2ce6f235-8140-4a4a-af0d-7553cd668ae4.png">

**Comment by chaoran-chen** [comment] 2022-10-21 12:57
That's a duplicate of #586 :)

**Closed as not planned by chaoran-chen** 2022-10-21 12:57 UTC
Labels: duplicate
