### ISSUE TITLE
[Feature request] Allow WHO name aliases in search queries

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#232] opened 2021-09-21 14:22 UTC
When querying for `Delta` + `mutation` (e.g. `S:Q613H`) I always have to type out `B.1.617.2*` which gets tedious.

It would be great if `Delta` (and other WHO names) were accepted in the query field. This could be done in the frontend, query URLs etc wouldn't have to be changed at all. All that'd be required is for a list of WHO VOCs to be provided and translated when clicking on search.

![image](https://user-images.githubusercontent.com/25161793/134188659-24a66fe2-5867-448a-95c0-8602b28f4c76.png)

**Comment by chaoran-chen** [comment] 2021-10-13 22:46
This is a duplicate of #203.

**Closed as completed by chaoran-chen** 2021-10-13 22:46 UTC
Labels: duplicate
