### ISSUE TITLE
BUG: Axis percentages are not well-chosen/formatted, e.g. ??9997% instead of 0.5,1,1.5 etc.

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#434] opened 2022-03-17 12:29 UTC
The y-axis tick labels are sometimes not rounded properly, this should be easy to fix and improve clarity a lot.

Right now, some of them are not legible at all. I get this for looking at the region plots:
<img width="2293" alt="image" src="https://user-images.githubusercontent.com/25161793/158808466-0fa412e8-ab5d-466a-a622-b1b06d152b3c.png">

Seems to be a floating point rounding bug. Only some of the floats are shown weirdly.

**Comment by chaoran-chen** [comment] 2022-04-12 14:50
I think that this is a duplicate of #325 fixed by @anastasia-escher in #457.

**Closed as completed by chaoran-chen** 2022-04-12 14:50 UTC
Labels: bug
