### ISSUE TITLE
Percentages in age plots add up to >>100%

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/cov-spectrum-website#172] opened 2021-06-15 18:07 UTC
Something is off with proportions by age, the percentages go way above 100% if added up.

https://cov-spectrum.ethz.ch/explore/Switzerland/AllSamples/AllTimes/variants/json=%7B%22variant%22%3A%7B%22name%22%3A%22B.1.1.7%22%2C%22mutations%22%3A[]%7D%2C%22matchPercentage%22%3A1%7D

![image](https://user-images.githubusercontent.com/25161793/122101984-3bedb000-ce15-11eb-862a-97ee8d38fca6.png)

**Comment by chaoran-chen** [comment] 2021-06-15 21:16
Thanks for the reminder, we really have to add descriptions..

What the plot shows is the number of cases of a variant in an age group divided by all cases in that age group.

**Comment by chaoran-chen** [comment] 2021-06-16 09:55
I'm closing it as it is not a bug. Adding documentation is covered in #133.

**Closed as completed by chaoran-chen** 2021-06-16 09:55 UTC

**Comment by chaoran-chen** [comment] 2021-06-17 19:42
What already existed:

![image](https://user-images.githubusercontent.com/18666552/122462420-dcc6a180-cfb4-11eb-80e9-58dbdff65571.png)

But of course, it's not very visible..

**Comment by corneliusroemer** [comment] 2021-06-17 19:45
Right now there's no indication of what the time frame is over which *all*
samples are counted. Is it the time selected at the top, that is last 3
months, 6 months etc.?

**Comment by chaoran-chen** [comment] 2021-06-17 19:48
Yes, what "all" is, is defined by the top filters, i.e. all filters in the selected country, timeframe, and all-vs.-surveillance.
