### ISSUE TITLE
Properly merge feature/model-chen2021Fitness

### ISSUE THREAD

**Issue by tehwalris** [GenSpectrum/cov-spectrum-website#52] opened 2021-03-12 11:11 UTC
Since it is not merged to develop at the moment, we can't make any changes to it. Make sure that the component respects the global `dataType` ("Sampling strategy") setting once you merge.

**Comment by chaoran-chen** [comment] 2021-03-12 11:19
Duplicate of #50 ;)

**Closed as completed by chaoran-chen** 2021-03-12 11:19 UTC
Labels: duplicate
